favicon: ../../assets/images/favicon.png

# navigation config
nav:
  # the title displays in the upper left corner which won't change
  title: Blog
  # the items displays in the upper right corner
  items:
    # these items will display as a link
    Archives: /archives
    Friends: /friends
    Projects: /projects
    About: /about
    # these will be automatically be an icon
    GitHub: https://github.com/MrWillCom
    CodePen: https://codepen.io/mrwillcom
    Patreon: https://www.patreon.com/MrWillCom
    Mastodon: https://noc.social/@MrWillCom
    Discord: https://discord.gg/UKuFDjcfY8
    Search: /search

# footer items
footer:
  # the title
  Blog:
    # the items after the title, display as links
    Blog: /
    Archives: /archives
    Tags: /tags
    Categories: /categories
  # also the title
  Projects:
    # the items
    RSA CLI: https://github.com/MrWillCom/rsa-cli
  # the title
  Me:
    # items
    GitHub: https://github.com/MrWillCom

# footer extra description
# footer_extra_description: something will be shown at the bottom of the footer

# the license your posts under
license: CC BY-NC 4.0
# the link of your license
license_link: https://creativecommons.org/licenses/by-nc/4.0
