name: Deploy Astro to GitHub Pages

on:
  push:
    branches: [main]

  workflow_dispatch:

# Allow job to clone the repo and deploy
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  generate-sitemap-and-build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '18'
        
        - name: Install dependencies in sanastro directory
          run: |
            cd sanastro
            npm install
        
        - name: Install xml2js
          run: npm install xml2js
        
        - name: Build
          # /dist is in .gitignore, so the files aren't present for draw.js to work with. Build is now included in the workflow so /dist will exist when the script runs.
          uses: withastro/action@v2
          with:
              path: sanastro # The root location of Astro project
          
          # Fallback:
          # working-directory: sanastro
          # run: npm run build
        
        - name: Generate diagram from sitemap
          run: node .github/scripts/draw.js
        
        - name: Copy sitemap.md to build output
          run: cp sanastro/src/content/blog/sitemap.md sanastro/dist/blog/sitemap.md

        # - name: Upload Pages artifact
        #   uses: actions/upload-pages-artifact@v3
        #   with:
        #     path: 'sanastro/dist'

  deploy:
    needs: generate-sitemap-and-build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        