on: push
name: Deploy sanalog.net via FTP on push
jobs:
  web-deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ftpupload.net
        username: epiz_27334897
        password: ${{ secrets.password }}
        server-dir: htdocs/sanalog.net/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          fileToExclude.txt
          README.md
          LICENSE
