name: Generate Sitemap Diagram

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build site
        run: npm run build
        
      - name: Install xml2js for parsing
        run: npm install xml2js
        
      - name: Generate diagram from sitemap
        run: node .github/scripts/draw.js
        
      # - name: Detect changes and commit, then push
      #   run: |
      #     git config --global user.name 'GitHub Action'
      #     git config --global user.email 'action@github.com'
      #     git add src/pages/sitsemap-diagram.md
      #     git diff --staged --quiet || git commit -m "Update sitemap diagram"
      #     git push